# Generated by Django 3.0.2 on 2020-01-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surename', models.CharField(max_length=200)),
            ],
        ),
    ]
